//
//  Location+HandWrittenMethods.m
//  Mobility
//
//  Created by Derrick Jones on 5/2/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//  Location.{h,m} are generated by Core Data automatically. In order
//  to avoid hand written code being overwritten by the tool, standard
//  practice is to create an Category on the object to separate
//  machine generated code and handwritten code

#import "Location+HandWrittenMethods.h"
#import "MobilityLogger.h"
@implementation Location (HandWrittenMethods)
- (void)setFieldsFromCLLocation:(CLLocation *)location {
    self.uuid = [MobilityLogger generateRandomUUID]; //the ohmage server expect this to be named "id", but "id" is a keyword in Obj-C
    self.latitude = [NSNumber numberWithDouble:location.coordinate.latitude];
    self.longitude = [NSNumber numberWithDouble:location.coordinate.longitude];
    self.speed = [NSNumber numberWithDouble:location.speed];
    NSTimeInterval t = [location.timestamp timeIntervalSince1970];
    self.time = [NSNumber numberWithUnsignedLongLong:(unsigned long long)(t * 1000)]; // timeinterval is typedef'ed to double, and represents seconds. server expects integer milliseconds
    self.timezone = [[NSTimeZone systemTimeZone] name];
    self.accuracy = [NSNumber numberWithDouble:location.horizontalAccuracy];
    self.provider = @"iOS Core Location";   
}
@end
